# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: sqlite3
  database: dev.db

test:
  adapter: sqlite3
  database: test.db

production:
  adapter: sqlite3
  database: prod.db
